// Mocks generated by Mockito 5.4.6 from annotations
// in mysivi_chat_app/test/features/chat/domain/usecases/send_message_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:mysivi_chat_app/features/chat/domain/entities/chat_session_entity.dart'
    as _i6;
import 'package:mysivi_chat_app/features/chat/domain/entities/message_entity.dart'
    as _i4;
import 'package:mysivi_chat_app/features/chat/domain/repositories/chat_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MessageEntity>> getMessages(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [userId]),
            returnValue: _i3.Future<List<_i4.MessageEntity>>.value(
              <_i4.MessageEntity>[],
            ),
          )
          as _i3.Future<List<_i4.MessageEntity>>);

  @override
  _i3.Future<void> sendMessage(String? userId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [userId, content]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> fetchReceiverMessage() =>
      (super.noSuchMethod(
            Invocation.method(#fetchReceiverMessage, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#fetchReceiverMessage, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> saveReceiverMessage(String? userId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#saveReceiverMessage, [userId, content]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.ChatSessionEntity>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i3.Future<List<_i6.ChatSessionEntity>>.value(
              <_i6.ChatSessionEntity>[],
            ),
          )
          as _i3.Future<List<_i6.ChatSessionEntity>>);

  @override
  _i3.Future<void> updateChatSession(
    String? userId,
    String? userName,
    String? lastMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateChatSession, [
              userId,
              userName,
              lastMessage,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markMessagesAsRead(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
