// Mocks generated by Mockito 5.4.6 from annotations
// in mysivi_chat_app/test/features/chat/presentation/cubit/chat_screen_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mysivi_chat_app/features/chat/domain/entities/message_entity.dart'
    as _i4;
import 'package:mysivi_chat_app/features/chat/domain/usecases/fetch_receiver_message_usecase.dart'
    as _i7;
import 'package:mysivi_chat_app/features/chat/domain/usecases/get_messages_usecase.dart'
    as _i2;
import 'package:mysivi_chat_app/features/chat/domain/usecases/save_receiver_message_usecase.dart'
    as _i9;
import 'package:mysivi_chat_app/features/chat/domain/usecases/send_message_usecase.dart'
    as _i5;
import 'package:mysivi_chat_app/features/chat/domain/usecases/update_chat_session_usecase.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetMessagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMessagesUseCase extends _i1.Mock
    implements _i2.GetMessagesUseCase {
  MockGetMessagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MessageEntity>> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i3.Future<List<_i4.MessageEntity>>.value(
              <_i4.MessageEntity>[],
            ),
          )
          as _i3.Future<List<_i4.MessageEntity>>);
}

/// A class which mocks [SendMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUseCase extends _i1.Mock
    implements _i5.SendMessageUseCase {
  MockSendMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? userId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId, content]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [UpdateChatSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateChatSessionUseCase extends _i1.Mock
    implements _i6.UpdateChatSessionUseCase {
  MockUpdateChatSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    String? userId,
    String? userName,
    String? lastMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId, userName, lastMessage]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FetchReceiverMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchReceiverMessageUseCase extends _i1.Mock
    implements _i7.FetchReceiverMessageUseCase {
  MockFetchReceiverMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(this, Invocation.method(#call, [])),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [SaveReceiverMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveReceiverMessageUseCase extends _i1.Mock
    implements _i9.SaveReceiverMessageUseCase {
  MockSaveReceiverMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? userId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId, content]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
