// Mocks generated by Mockito 5.4.6 from annotations
// in mysivi_chat_app/test/features/users/data/repositories/users_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mysivi_chat_app/core/models/chat_session_model.dart' as _i6;
import 'package:mysivi_chat_app/core/models/message_model.dart' as _i5;
import 'package:mysivi_chat_app/core/models/user_model.dart' as _i4;
import 'package:mysivi_chat_app/core/services/storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i3.Future<List<_i4.UserModel>>.value(
              <_i4.UserModel>[],
            ),
          )
          as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Future<void> saveUsers(List<_i4.UserModel>? users) =>
      (super.noSuchMethod(
            Invocation.method(#saveUsers, [users]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.MessageModel>> getMessages(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [userId]),
            returnValue: _i3.Future<List<_i5.MessageModel>>.value(
              <_i5.MessageModel>[],
            ),
          )
          as _i3.Future<List<_i5.MessageModel>>);

  @override
  _i3.Future<void> saveMessages(
    String? userId,
    List<_i5.MessageModel>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessages, [userId, messages]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.ChatSessionModel>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i3.Future<List<_i6.ChatSessionModel>>.value(
              <_i6.ChatSessionModel>[],
            ),
          )
          as _i3.Future<List<_i6.ChatSessionModel>>);

  @override
  _i3.Future<void> saveChatSessions(List<_i6.ChatSessionModel>? sessions) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatSessions, [sessions]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
